platform :ios, '13.0'

# Disable CocoaPods analytics to speed up installation
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define workspace mapping for Xcode
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Use frameworks and modular headers for all pods
use_frameworks!
use_modular_headers!

target 'Runner' do
  pod 'Flutter', :path => 'Flutter'

  # Flutter plugins used by this project.
  pod 'cloud_firestore',    :path => 'Flutter/ephemeral/.symlinks/plugins/cloud_firestore/ios'
  pod 'firebase_auth',      :path => 'Flutter/ephemeral/.symlinks/plugins/firebase_auth/ios'
  pod 'firebase_core',      :path => 'Flutter/ephemeral/.symlinks/plugins/firebase_core/ios'
  pod 'flutter_webrtc',     :path => 'Flutter/ephemeral/.symlinks/plugins/flutter_webrtc/ios'
  pod 'path_provider_ios',  :path => 'Flutter/ephemeral/.symlinks/plugins/path_provider_ios/ios'
  pod 'file_picker',        :path => 'Flutter/ephemeral/.symlinks/plugins/file_picker/ios'
end

# Post-installation hook to remove unsupported compiler flags and set deployment target
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Remove unsupported '-gmodules' flag from OTHER_CFLAGS
      other_cflags = config.build_settings['OTHER_CFLAGS']
      if other_cflags && other_cflags.include?('gmodules')
        config.build_settings['OTHER_CFLAGS'] = other_cflags.gsub('gmodules', '')
      end
      # Ensure each pod has a minimum deployment target of 13.0
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
    flutter_additional_ios_build_settings(target)
  end
end
