include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: false
    unnecessary_this: true
    always_declare_return_types: true

analyzer:
  language:
    strict-raw-types: true
  errors:
    unused_import: warning
    dead_code: warning
